version: "3"

services:
  izumi: 
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      IZUMI_DATA_DIR: /data/izumi
      http_proxy: http://127.0.0.1:7890
      https_proxy: http://127.0.0.1:7890
      all_proxy: http://127.0.0.1:7890
    ports:
      - "8888:80"
    volumes:
      - ./data/db/:/data/db
      - ./data/izumu:/data/izumi
      - ./log:/app/log # optional
    restart: always
