version: "3"

services:
  izumi: 
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      IZUMI_DATA_DIR: /data/izumi
      http_proxy: socks5://192.168.1.4:20170
      https_proxy: socks5://192.168.1.4:20170
      all_proxy: socks5://192.168.1.4:20170
    ports:
      - "8888:80"
    volumes:
      - ./data/db/:/data/db
      - ./data/izumu:/data/izumi
      - ./log:/app/log # optional
    restart: always
