[supervisord]
nodaemon=true
logfile=/app/log/supervisord.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
priority=10
autostart=true
autostart=true

[program:server]
command=/app/server
directory=/app
priority=20
autostart=true
autorestart=true
stdout_logfile=/app/log/server.log
stderr_logfile=/app/log/server.log