postgresql:
  host: 127.0.0.1
  port: 5432
  username: hermes
  database: hermes
  password: hermes
app: 
  port: 19876
log:
  - filename: ./log/info.log
    level_range: "[info,error)"
  - filename: ./log/error.log
    level_range: "[error,)"
