postgresql:
  host: 127.0.0.1
  port: 15432
  username: postgres
  database: hermes
  password: root
app: 
  port: 19876
log:
  - filename: ./log/info.log
    level_range: "[info,error)"
  - filename: ./log/error.log
    level_range: "[error,)"
proxy:
  scheme: socks5
  host: 127.0.0.1
  port: 7890
