postgresql:
  host: hermes-postgres-1
  port: 5432
  username: hermes
  database: hermes
  password: 1234567
app: 
  port: 19876
log:
  - filename: ./log/info.log
    level_range: "[info,error)"
  - filename: ./log/error.log
    level_range: "[error,)"
